# Generated by Django 4.2.7 on 2023-11-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPNStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('transitions', models.PositiveIntegerField(default=0)),
                ('uploaded_data', models.PositiveIntegerField(default=0)),
                ('downloaded_data', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
