# Generated by Django 4.2.7 on 2023-11-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_service', '0002_alter_site_name'),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnstatistic',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vpn_service.site'),
        ),
    ]
